version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: booktracker_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Left4de@d123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./populate_db.sql:/docker-entrypoint-initdb.d/populate_db.sql

  app:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      host: db
      database: booktracker_db
      user: admin
      password: Left4de@d123
      port: 5432 # Inside the container, it will use the default PostgreSQL port

volumes:
  pgdata:
