version: "3.8"

services:
  db:
    image: postgres:latest
    # environment:
    #   POSTGRES_DB:
    #   POSTGRES_USER:
    #   POSTGRES_PASSWORD:
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./populate_db.sql:/docker-entrypoint-initdb.d/populate_db.sql

  app:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    # environment:
    #   host:
    #   database:
    #   user:
    #   password:
    #   port: # Inside the container, it will use the default PostgreSQL port

volumes:
  pgdata:
